export const LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const LOGIN_REQUEST_FINISHED = 'AUTH_LOGIN_REQUEST_FINISHED';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const AUTH_REFRESH_TOKEN_FINISHED = 'AUTH_REFRESH_TOKEN_FINISHED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH_USER = 'AUTH_UPDATE_USER';
